// Generated by CoffeeScript 1.10.0
(function() {
  var commandHtml, terminalHtml;

  terminalHtml = '<section class="terminal col-md-12"> <div class="command"> <input type="text" class="form-control"> <span class="add-command">Add Command</span> <span class="delete-command">Delete</span> </div> <div class="control"> <span class="add-terminal">Add Terminal</span> <span class="delete-terminal">Delete</span> </div> </section>';

  commandHtml = '<div class="command"> <input type="text" class="form-control"> <span class="add-command">Add Command</span> <span class="delete-command">Delete</span> </div>';

  $(".terminal-container").delegate(".add-terminal", "click", function() {
    $(this).parent().parent().parent().append(terminalHtml);
    if ($(".terminal").length > 1) {
      return $(".delete-terminal").show();
    }
  });

  $(".terminal-container").delegate(".delete-terminal", "click", function() {
    if ($(this).parent().parent().parent().find(".terminal").length === 1) {
      return;
    }
    return $(this).parent().parent().remove();
  });

  $(".terminal-container").delegate(".add-command", "click", function() {
    $(commandHtml).insertBefore($(this).parent().parent().find(".control"));
    if ($(this).parent().parent().find(".command").length > 1) {
      return $(".delete-command").show();
    }
  });

  $(".terminal-container").delegate(".delete-command", "click", function() {
    if ($(this).parent().parent().find(".command").length === 1) {
      return;
    }
    return $(this).parent().remove();
  });

  $(document).delegate("input", "keyup", function() {
    var singleTerminal;
    singleTerminal = "<p>#!/bin/bash</p>";
    $(".terminal").each(function() {
      var commandChildren;
      singleTerminal += "<p>osascript -e 'tell application \"Terminal\" to do script \"";
      commandChildren = $(this).children(".command");
      commandChildren.each(function(index) {
        singleTerminal += $(this).find("input").val();
        if (index !== commandChildren.length - 1) {
          return singleTerminal += " && ";
        }
      });
      return singleTerminal += "\"'</p>";
    });
    $("#result").empty();
    return $("#result").append(singleTerminal);
  });

}).call(this);
