// Generated by CoffeeScript 1.10.0
(function() {
  var callSortable, clipboard, commandHtml, generate, terminalHtml;

  terminalHtml = '<section class="terminal col-md-12"> <div class="command-container"> <div class="command"> <input type="text" class="form-control"> <span class="add-command">Add Command</span> <span class="delete-command">Delete</span> <i class="fa fa-arrows-alt" aria-hidden="true"></i> </div> </div> <div class="control"> <span class="add-terminal">Add Terminal</span> <span class="delete-terminal">Delete</span> <i class="fa fa-arrows-alt" aria-hidden="true"></i> </div> </section>';

  commandHtml = '<div class="command"> <input type="text" class="form-control"> <span class="add-command">Add Command</span> <span class="delete-command">Delete</span> <i class="fa fa-arrows-alt" aria-hidden="true"></i> </div>';

  $(".terminal-container").delegate(".add-terminal", "click", function() {
    $(this).parent().parent().parent().append(terminalHtml);
    if ($(".terminal").length > 1) {
      $(".delete-terminal").show();
    }
    return callSortable();
  });

  $(".terminal-container").delegate(".delete-terminal", "click", function() {
    if ($(this).parent().parent().parent().find(".terminal").length === 1) {
      return;
    }
    return $(this).parent().parent().remove();
  });

  $(".terminal-container").delegate(".add-command", "click", function() {
    $(this).parent().parent().append(commandHtml);
    if ($(this).parent().parent().find(".command").length > 1) {
      $(".delete-command").show();
    }
    return callSortable();
  });

  $(".terminal-container").delegate(".delete-command", "click", function() {
    if ($(this).parent().parent().find(".command").length === 1) {
      return;
    }
    return $(this).parent().remove();
  });

  generate = function() {
    var singleTerminal;
    singleTerminal = "<p>#!/bin/bash</p>";
    $(".terminal").each(function() {
      var commandChildren;
      singleTerminal += "<p>osascript -e 'tell application \"Terminal\" to do script \"";
      commandChildren = $(this).find(".command-container").children(".command");
      commandChildren.each(function(index) {
        singleTerminal += $(this).find("input").val();
        if (index !== commandChildren.length - 1) {
          return singleTerminal += " && ";
        }
      });
      return singleTerminal += "\"'</p>";
    });
    $("#result").empty();
    return $("#result").append(singleTerminal);
  };

  $(document).delegate("input", "keyup", function() {
    return generate();
  });

  clipboard = new Clipboard('.copy-code');

  new Clipboard('.copy-code', {
    text: function(trigger) {
      var clipboardText;
      clipboardText = "";
      $("#result p").each(function() {
        return clipboardText += $(this).text() + "\n";
      });
      return clipboardText;
    }
  });

  callSortable = function() {
    $(".terminal-container, .command-container").sortable({
      stop: function(event, ui) {
        return generate();
      }
    });
    return $(".terminal-container, .command-container").disableSelection();
  };

  callSortable();

}).call(this);
